
(executable
 (name fablejs)
 (modules fablejs)
 (libraries brr fabula)
 (modes js))

(rule
 (deps story.html)
 (action
   (with-stdout-to embedded.ml
     (progn
       (echo "let index = {fable|")
       ; (cat story.html)
       (run sed s@_build/default/fablejs.bc.js@fablejs.bc.js@ story.html)
       (echo "|fable}")
       (echo "let default_css = {fable|")
       (cat default.css)
       (echo "|fable}")
       (echo "let fablejs = {fable|")
       (cat fablejs.bc.js)
       (echo "|fable}")
       (echo "let runtime = {fable|")
       (cat runtime.js)
       (echo "|fable}")
       (echo "let main_browser = {fable|")
       (cat main_browser.js)
       (echo "|fable}")
       (echo "let test = {fable|")
       (cat test/runtime.t/test.js)
       (echo "|fable}")))))

(executable
 (name fable)
 (public_name fable)
 (modules fable embedded)
 (libraries fabula)
 (preprocess (pps ppx_deriving_yojson ppx_deriving.std)))

(env (dev
 (flags (:standard -warn-error -A))
 ; source maps cause a crash in vite if enabled
 (js_of_ocaml (sourcemap no))))

(subdir deploy
 (rule
  (alias editor)
  (deps ../story.html
   (glob_files ../web/*)
   (glob_files ../examples/*.md)
   ../editor/examples.sh ../editor/editor.html)
  (action (progn
   (copy ../fablejs.bc.js fablejs.bc.js)
   (copy ../editor/editor.js editor.js)
   ; (copy ../editor/editor.html index.html)
   (with-stdout-to index.html
    (run ../editor/examples.sh ../editor/editor.html))
   ; (copy ../story.html story.html)
   (with-stdout-to story.html
    (run sed -e s/%s// -e s@_build/default/fablejs.bc.js@fablejs.bc.js@ -e s@{{extra}}@@ ../story.html))
   (write-file story.js "var story = {frontmatter: {}, scenes: []};")
   (copy ../runtime.js runtime.js)
   (copy ../main_browser.js main_browser.js)
   (copy ../default.css default.css)))))
